invoices/controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Status;
use Yii;
use app\models\User;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

class AdminController extends Controller
{
    public function actionIndex()
    {
        if (Yii::$app->user->can('admin')) {

            $query = User::find()->joinWith(['role']);

            $provider = new ActiveDataProvider([
                'sort' => false,
                'query' => $query,
                'pagination' => [
                    'pageSize' => 10,
                ],

            ]);

            return $this->render('index', ['dataProvider' => $provider, 'pagination' => $provider->getPagination()]);

        } else {

            throw new ForbiddenHttpException('Log in as admin to proceed!');

        }

    }

    public function actionChangeStatus($userId = -1)
    {
        if (Yii::$app->user->can('admin')) {

            if (!$user = User::findOne(['userId' => $userId])) {

                throw new NotFoundHttpException('User not found!');

            }

            $user->scenario = User::SCENARIO_CHANGE_STATUS;

            if ($user->statusId == Status::STATUS_ACTIVE) {

                $user->statusId = Status::STATUS_INACTIVE;

            } else {

                $user->statusId = Status::STATUS_ACTIVE;

            }

            $user->save();

            $this->redirect(Yii::$app->request->referrer);

        } else {

            throw new ForbiddenHttpException('Log in as admin to proceed!');

        }


    }


}

invoices/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionRegister()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new User(['scenario' => User::SCENARIO_REGISTER]);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            $imageFile = UploadedFile::getInstance($model, 'imageFile');

            if ($imageFile != null) {

                //has as filename to check later if such file was already uploaded
                $avatarFilePath = User::AVATAR_FILE_PATH . hash_file('md5', $imageFile->tempName) . "." . $imageFile->extension;

                $imageFile->saveAs($avatarFilePath);
                $model->avatar = $avatarFilePath;

            } else {

                $model->avatar = User::DEFAULT_AVATAR_FILE_PATH;

            }

            //autologin
            $identity = new LoginForm($model->email, $model->password);

            $model->save();

            $userRoleName = Yii::$app->authManager->getRole('user');
            Yii::$app->authManager->assign($userRoleName, $model->userId);

            $identity->login();

            return $this->redirect('/');
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionPasswordRestore()
    {
        //enterEmail -> get link to the password restore window
    }

}

invoices/controllers/UserController.php
<?php

namespace app\controllers;

use yii;
use app\models\User;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\UnauthorizedHttpException;

class UserController extends Controller
{
    public function actionIndex($userId = null)
    {

        if (Yii::$app->user->can('user')) {


            if ($userId == null) {
                $userId = Yii::$app->user->id;
            } else {
                if (!Yii::$app->user->can('admin')) {
                    //mb need to throw not found
                    throw new UnauthorizedHttpException('Log is as admin!');
                }
            }

            $model = User::findById($userId);

            $model->scenario = User::SCENARIO_EDIT;

            unset($model->password);

            if ($model->load(Yii::$app->request->post()) && $model->validate()) {

                    $imageFile = UploadedFile::getInstance($model, 'imageFile');

                    if ($imageFile != null) {

                        //has as filename to check later if such file was already uploaded
                        $avatarFilePath = User::AVATAR_FILE_PATH . hash_file('md5', $imageFile->tempName) . "." . $imageFile->extension;

                        $imageFile->saveAs($avatarFilePath);
                        $model->avatar = $avatarFilePath;

                    }

                $model->save();

            }


            return $this->render('index', ['model' => $model]);

        } else {

            throw new UnauthorizedHttpException('Please, log in first!');

        }
    }

    public function actionChangePassword()
    {
        if (Yii::$app->user->can('user')) {

            //changepass

        } else {

            throw new UnauthorizedHttpException('Please, log in first!');

        }
    }
}

invoices/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $items = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];

    if (Yii::$app->user->can('admin')) {

        $items[] = ['label' => 'All Users', 'url' => ['/admin/index']];
    }

    if (Yii::$app->user->isGuest) {
        $items[] = ['label' => 'Register', 'url' => ['/site/register']];
        $items[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $items[] = ['label' => 'My Invoices', 'url' => ['/invoices/index']];
        $items[] = ['label' => 'My Clients', 'url' => ['/clients/index']];
        $items[] = ['label' => 'My Profile', 'url' => ['/user/index']];
        $items[] = [
            'label' => 'Logout',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">

    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>