invoices/models/Clients.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "clients".
 *
 * @property string $clientId
 * @property string $firstName
 * @property string $lastName
 * @property string $phone
 * @property string $email
 * @property string $organization
 * @property string $addressId
 * @property string $lastInvoice
 * @property double $totalSpentCount
 */
class Clients extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clients';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['firstName', 'lastName', 'phone', 'email', 'organization'], 'required'],

            ['addressId', 'integer'],

            [['lastInvoice'], 'safe'],

            [['totalSpentCount'], 'number'],

            [['firstName', 'lastName', 'email', 'organization'], 'string', 'max' => 255],

            ['email', 'email'],

            ['phone', 'match', 'pattern' => '/[0-9]/', 'message' => 'Invalid phone number!'],

            ['phone', 'match', 'pattern' => '/^[0-9\-\(\)]{6,32}$/', 'message' => 'Please, use only digits, dashes and parenthesis!'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'clientId' => 'Client ID',
            'firstName' => 'First Name',
            'lastName' => 'Last Name',
            'phone' => 'Phone',
            'email' => 'E-mail',
            'organization' => 'Organization',
            'addressId' => 'Address ID',
            'lastInvoice' => 'Last Invoice',
            'totalSpentCount' => 'Total Spent Count',
        ];
    }


    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['statusId' => 'statusId']);
    }

    public function getAddress()
    {
        return $this->hasOne(Address::className(), ['addressId' => 'addressId']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            if ($this->isNewRecord) {
                    $this->statusId = Status::STATUS_ACTIVE;
            }

            return true;
        }

        return false;

    }



    public static function checkClientExists($clientModel)
    {
        //if exact same address already exists -> give its id
        if ($client = Clients::findOne([
            'firstName' => $clientModel->firstName,
            'lastName' => $clientModel->lastName,
            'phone' => $clientModel->phone,
            'email' => $clientModel->email,
            'organization' => $clientModel->organization,
        ])) {
            return $client->clientId;
        }
    }


}

invoices/controllers/ClientsController.php
<?php

namespace app\controllers;

use app\models\Status;
use Yii;
use app\models\Address;
use app\models\Clients;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

class ClientsController extends Controller
{
    public function actionIndex()
    {
        if (Yii::$app->user->can('user')) {

            $query = Clients::find()->where(['statusId' => Status::STATUS_ACTIVE]);

            $provider = new ActiveDataProvider([
                'sort' => false,
                'query' => $query,
                'pagination' => [
                    'pageSize' => 10,
                ],
            ]);

            return $this->render('index', ['dataProvider' => $provider, 'pagination' => $provider->getPagination()]);

        } else {

            throw new ForbiddenHttpException('Please, log in or sign up first!');

        }

    }

    public function actionAddClient()
    {

        if (Yii::$app->user->can('user')) {

            $client = new Clients();
            $address = new Address();

            if ($client->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post()) && $client->validate() && $address->validate()) {

                if ($id = Address::checkAddressExists($address)) {

                    $address = Address::findOne(['addressId' => $id]);

                } else {

                    $address->save();
                }

                $client->addressId = $address->getPrimaryKey();
                $client->save();

                return $this->redirect('/clients/index');
            }

            return $this->render('add', ['client' => $client, 'address' => $address]);

        } else {

            throw new ForbiddenHttpException('Please, log in or sign up first!');

        }

    }

    public function actionEdit($clientId = -1)
    {
        if (Yii::$app->user->can('user')) {

            if ($client = Clients::findOne(['clientId' => $clientId])) {

                $address = Address::findOne(['addressId' => $client->addressId]);

                if ($client->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post()) && $client->validate() && $address->validate()) {

                    if ($id = Address::checkAddressExists($address)) {

                        $address = Address::findOne(['addressId' => $id]);

                    } else {

                        $address->save();
                    }

                    $client->addressId = $address->getPrimaryKey();
                    $client->save();

                    return $this->redirect('/clients/index');
                }

                return $this->render('edit', ['client' => $client, 'address' => $address]);

            } else {
                throw new NotFoundHttpException('Client was not found.');
            }

        } else {

            throw new ForbiddenHttpException('Please, log in or sign up first!');

        }
    }

    public function actionDelete($clientId = -1)
    {
        if (Yii::$app->user->can('user')) {

            if ($client = Clients::findOne(['clientId' => $clientId])) {

                if (Yii::$app->request->post()) {


                    $client->statusId = Status::STATUS_INACTIVE;
                    $client->save();

                    return $this->redirect('/clients/index');
                }

                return $this->render('delete', ['client' => $client]);

            } else {
                throw new NotFoundHttpException('Contact was not found.');
            }

        } else {

            throw new ForbiddenHttpException('Please, log in or sign up first!');

        }
    }

    //

}

invoices/views/clients/add.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Add client';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please, fill out the following fields to add a new client:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'register-form',
        'options' => [
            'class' => 'form-horizontal',
            //'enctype' => 'multipart/form-data'
        ],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <p>
        Client Information
    </p>

    <?= $form->field($client, 'firstName') ?>

    <?= $form->field($client, 'lastName') ?>

    <?= $form->field($client, 'email') ?>

    <?= $form->field($client, 'phone') ?>

    <?= $form->field($client, 'organization') ?>

    <p>
        Client address
    </p>

    <?= $form->field($address, 'addressLine1') ?>

    <?= $form->field($address, 'addressLine2') ?>

    <?= $form->field($address, 'city') ?>

    <?= $form->field($address, 'country') ?>

    <?= $form->field($address, 'state') ?>

    <?= $form->field($address, 'zip') ?>



    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Add', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

            <?= Html::button('Cancel', ['class' => 'btn btn-primary', 'onclick' => "window.location.href='/clients/index'"]) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

invoices/views/clients/delete.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Delete client';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please, fill out the following fields to add a new client:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'register-form',
        'options' => [
            'class' => 'form-horizontal',
        ],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <p>
        Client Information
    </p>

    <?= $form->field($client, 'firstName')->textInput(['readonly' => true]) ?>

    <?= $form->field($client, 'lastName')->textInput(['readonly' => true]) ?>

    <?= $form->field($client, 'email')->textInput(['readonly' => true]) ?>

    <?= $form->field($client, 'phone')->textInput(['readonly' => true]) ?>

    <?= $form->field($client, 'organization')->textInput(['readonly' => true]) ?>



    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Delete', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

            <?= Html::button('Cancel', ['class' => 'btn btn-primary', 'onclick' => "window.location.href='/clients/index'"]) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

invoices/views/clients/edit.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Edit client';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please, fill out the following fields to edit client:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'register-form',
        'options' => [
            'class' => 'form-horizontal',
            //'enctype' => 'multipart/form-data'
        ],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <p>
        Client Information
    </p>

    <?= $form->field($client, 'firstName') ?>

    <?= $form->field($client, 'lastName') ?>

    <?= $form->field($client, 'email') ?>

    <?= $form->field($client, 'phone') ?>

    <?= $form->field($client, 'organization') ?>

    <p>
        Client address
    </p>

    <?= $form->field($address, 'addressLine1') ?>

    <?= $form->field($address, 'addressLine2') ?>

    <?= $form->field($address, 'city') ?>

    <?= $form->field($address, 'country') ?>

    <?= $form->field($address, 'state') ?>

    <?= $form->field($address, 'zip') ?>



    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Edit', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

            <?= Html::button('Cancel', ['class' => 'btn btn-primary', 'onclick' => "window.location.href='/clients/index'"]) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

invoices/views/clients/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */


use yii\helpers\Html;
use yii\grid\GridView;

$this->title = 'My Clients';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Html::a('Add Client', ['/clients/add-client'])?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'format' => 'text',
                'label' => 'Name',
                'value' => function ($data) {
                    return $data->firstName . " " . $data->lastName;
                },
            ],
            'phone',
            'email',
            'organization',
            [
                'format' => 'text',
                'label' => 'Last Invoice',
                'value' => function ($data) {
                    if ($data->lastInvoice == '0000-00-00') {
                        return 'No invoices yet.';
                    } else {
                        return $data->lastInvoice;
                    }
                },
            ],
            [
                'format' => 'text',
                'label' => 'Total Spent Count',
                'value' => function ($data) {
                    return "$ " . $data->totalSpentCount;
                },
            ],
            [
                'format' => 'raw',
                //'label' => 'edit/delete options',
                'value' => function ($data) {
                    $links = Html::a(Html::img('/img/system/edit.png'), "/clients/edit/$data->clientId") . ' ';
                    /*
                     * button changes depending on current status
                    if (//checkStatus) {*/
                        $links .= Html::a(Html::img('/img/system/delete.png'), "/clients/delete/$data->clientId");
                    /*} else {
                        $links .= Html::a(Html::img('/img/system/inactive.png'), "/admin/change-status/$data->userId");
                    }
                    */
                    return $links;
                }
            ],
        ],
    ]) ?>

</div>